name: 🚀 Deploy to Server

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        type: choice
        options:
          - development
          - production

env:
  NODE_VERSION: "18"

jobs:
  build:
    name: 🔨 Build Project
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 🔧 Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: 📦 Install Dependencies
        run: npm ci --only=production

      - name: 🔨 Build Project
        run: npm run build

      - name: 🗄️ Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-and-modules
          path: |
            dist/
            node_modules/
            package.json
            ecosystem.config.js
            prisma/

  deploy:
    name: 🚀 Deploy to ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    needs: build
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: 📥 Download production artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-and-modules
          path: .

      - name: 🚚 Transfer files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "dist/,node_modules/,package.json,ecosystem.config.js,prisma/"
          target: "/var/www/backend-api"
          strip_components: 1

      - name: 🔄 Restart application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /var/www/backend-api
            npx prisma db push --accept-data-loss
            pm2 reload ecosystem.config.js --env ${{ github.event.inputs.environment }}
