# Pipeline'ın türünü ve adını belirtir
kind: pipeline
type: docker
name: Sunucuya Gonder

# Bu pipeline'ı hangi olayın tetikleyeceğini belirtir
trigger:
  branch:
    - main # Sadece 'main' branch'ine kod gonderildiginde calisir
  event:
    - push

# Çalıştırılacak adımlar
steps:
- name: SSH ile sunucuya dağıtım yap
  # Kullanılacak Docker imajı (sizin log'unuzdaki ile aynı)
  image: appleboy/drone-ssh:1.8.1
  
  # Plugin'e gönderilecek ayarlar
  settings:
    # 1. Sunucu adresi (ZORUNLU - hatanızın sebebi buydu)
    # Kendi sunucunuzun IP adresini veya alan adını yazın
    host: 176.96.131.222
    # 2. Sunucuya bağlanılacak kullanıcı adı
    username: root

    # 3. Sunucu SSH portu (genellikle 22'dir)
    port: 22

    # 4. Sunucu şifresi (GÜVENLİ YÖNTEM)
    # Şifreyi asla doğrudan buraya yazmayın!
    # Drone arayüzünden 'ssh_password' adında bir secret oluşturun.
    password:
      from_secret: Manavgat07

    # 5. Sunucuda çalıştırılacak komutlar
    # Kendi komutlarınızı bu bölüme yazın
    script:
      - echo "Sunucuya başarıyla bağlandım."
      - cd /var/www/html # Projenizin sunucudaki konumu
      - git pull origin main # Değişiklikleri çek
      - echo "Uygulama başarıyla güncellendi."
      # Gerekirse servis yeniden başlatma komutları vb. ekleyebilirsiniz
      # - sudo systemctl restart nginx
