# İş akışının adı (GitHub Actions arayüzünde görünür)
name: Main Branch Loglama

# Bu iş akışının ne zaman tetikleneceğini belirler
on:
  # SADECE "main" branch'ine bir push (kod gönderme) yapıldığında çalışır
  push:
    branches:
      - main

# Çalıştırılacak işlerin listesi
jobs:
  # "merhaba-de" adında tek bir iş tanımlıyoruz
  merhaba-de:
    # Bu işin çalışacağı sanal makinenin işletim sistemi
    runs-on: ubuntu-latest

    # İşin içinde sırayla çalıştırılacak adımlar
    steps:
      # Adım 1: "run" komutu ile doğrudan bir terminal komutu çalıştırıyoruz.
      # Bu adım, log'a "merhaba log" mesajını yazdıracaktır.
      - name: Log Mesajını Yazdır
        run: echo "merhaba log"
