# İş akışının adı (GitHub Actions arayüzünde görünür)
name: SSH ile Sunucuya Bağlan

# Bu iş akışının ne zaman tetikleneceğini belirler
on:
  # SADECE "main" branch'ine bir push (kod gönderme) yapıldığında çalışır
  push:
    branches:
      - main

# Çalıştırılacak işlerin listesi
jobs:
  # "sunucuya-baglan" adında bir iş
  sunucuya-baglan:
    # Bu işin çalışacağı sanal makinenin işletim sistemi
    runs-on: ubuntu-latest

    # İşin içinde sırayla çalıştırılacak adımlar
    steps:
      # Adım 1: SSH bağlantısı kuran ve komut çalıştıran eylem
      - name: Sunucuya SSH ile bağlan ve komut çalıştır
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22 # Varsayılan port 22'dir, farklıysa değiştirin.
          script: |
            echo "Sunucuya başarıyla bağlandım!"
            ls -la
            # Buraya sunucuda çalıştırmak istediğiniz diğer komutları ekleyebilirsiniz.
