name: SSH ile Sunucuya Bağlan

# Bu iş akışının ne zaman tetikleneceğini belirler
on:
  # SADECE "main" branch'ine bir push (kod gönderme) yapıldığında çalışır
  push:
    branches:
      - main

# Çalıştırılacak işlerin listesi
jobs:
  # "sunucuya-baglan" adında bir iş
  sunucuya-baglan:
    # Bu işin çalışacağı sanal makinenin işletim sistemi
    runs-on: ubuntu-latest

    # İşin içinde sırayla çalıştırılacak adımlar
    steps:
      # Adım 1: SSH bağlantısı kuran ve komut çalıştıran eylem
      - name: Sunucuya SSH ile bağlan ve komut çalıştır
        uses: appleboy/ssh-action@master
        with:
          host: "176.96.131.222"
          username: "root"
          password: "Manavgat07!"
          port: 22 # Varsayılan port 22'dir, farklıysa değiştirin.
          script: |
            echo "Sunucuya başarıyla bağlandım!"
            # Eğer proje klasörü varsa sil
            if [ -d "/root/api" ]; then
              rm -rf /root/api
            fi
            # Projeyi GitHub'dan çek
            cd /root
            git clone https://github.com/Top-Pesinde/backend.git api
            cd api
            echo "Proje başarıyla güncellendi!"

            # Docker konteynerlerini kontrol et ve güncelle
            if docker ps &>/dev/null; then
              echo "Docker servisi çalışıyor, konteynerler kontrol ediliyor..."
              # Eğer konteynerler zaten çalışıyorsa sadece güncelle
              if docker ps | grep -q "express-api"; then
                echo "Mevcut konteynerler güncelleniyor..."
                docker-compose down
                docker-compose up -d
              else
                echo "Konteynerler ilk kez başlatılıyor..."
                docker-compose up -d
              fi
            else
              echo "Docker servisi başlatılıyor..."
              systemctl start docker
              echo "Konteynerler başlatılıyor..."
              docker-compose up -d
            fi

            echo "Deployment tamamlandı!"
